---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kalle.
--- DateTime: 04.11.19 19:55
---
project "ImGui"
kind "StaticLib"
language "C++"
cppdialect "C++17"
staticruntime "on"

targetdir ("bin/" .. outputdir .. "/%{prj.name}")
objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

files{
    "imconfig.h",
    "imgui.h",
    "imgui.cpp",
    "imgui_draw",
    "imgui_internal",
    "imgui_widgets.cpp",
    "imstb_rectpack.h",
    "imstb_textedit",
    "imstb_truetype",
    "imgui_demo.cpp",
}

filter "system:windows"
systemversion "latest"

filter "configurations:Debug"
		runtime "Debug"
		symbols "on"

	filter "configurations:Release"
		runtime "Release"
		optimize "on"